version: '3.8'

services:
  frontend:
    build: .
    container_name: alertas_frontend
    ports:
      - "5555:80" # Mapeamos el puerto 80 del Nginx a un puerto poco común externo (5555)
    restart: unless-stopped
