server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Esto asegura que React/Vite manejen bien las rutas (SPA)
    # y no tire error 404 al recargar la página.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
